local _, namespace = ...

local L = setmetatable({}, { __index = function(t, k)
	local v = tostring(k)
	rawset(t, k, v)
	return v
end })

namespace.L = L

local LOCALE = GetLocale()

if LOCALE == "enUS" or LOCALE == "enGB" then
	-- No translation needed for english client, so we simply return
	return 
end


if LOCALE == "zhCN" then
	-- Simplified Chinese translations go here
	-- Thanks to ming1455 for the translation!
	
			-- Exclusively Talent Cooldowns
		L["Blade Flurry"] = "剑刃乱舞"
		L["Adrenaline Rush"] = "冲动"
		L["Preparation"] = "伺机待发"
		L["Ghostly Strike"] = "鬼魅攻击"
		L["Premeditation"] = "预谋"
		L["Cold Blood"] = "冷血"

		L["Bestial Wrath"] = "血性狂暴"
		L["Intimidation"] = "胁迫"
		L["Scatter Shot"] = "驱散射击"
		L["Aimed Shot"] = "瞄准射击"
		L["Deterrence"] = "威慑"

		L["Last Stand"] = "破釜沉舟"
		L["Sweeping Strikes"] = "横扫攻击"
		L["Death Wish"] = "死亡之愿"
		L["Concussion Blow"] = "震荡猛击"

		L["Inner Focus"] = "心灵专注"
		L["Power Infusion"] = "能量灌注"
		L["Silence"] = "沉默"

		L["Elemental Mastery"] = "元素掌握"
		L["Stormstrike"] = "风暴打击"
		L["Nature's Swiftness"] = "自然迅捷"

		L["Fel Domination"] = "恶魔支配"
		L["Amplify Curse"] = "诅咒增幅"

		L["Divine Favor"] = "神恩术"
		L["Holy Shock"] = "神圣震击"
		L["Holy Shield"] = "神圣之盾"
		L["Repentance"] = "忏悔"

		L["Innervate"] = "激活"
		L["Faerie Fire (Feral)"] = "精灵之火（野性）"
		L["Feral Charge"] = "野性冲锋"
		L["Swiftmend"] = "迅捷治愈"

		L["Presence of Mind"] = "气定神闲"
		L["Arcane Power"] = "奥术强化"
		L["Combustion"] = "燃烧"
		L["Cold Snap"] = "急速冷却"
		L["Ice Block"] = "寒冰屏障"

		-- Trinkets & Racials
		L["Will of the Forsaken"] = "被遗忘者的意志"
		L["Perception"] = "感知"
		L["War Stomp"] = "战争践踏"
		L["Stoneform"] = "石像形态"
		L["Cannibalize"] = "食尸"
		L["Blood Fury"] = "血性狂暴"
		L["Berserking"] = "狂暴"
		L["Shadowmeld"] = "影遁"
		L["Escape Artist"] = "逃命专家"

		L["Brittle Armor"] = "脆弱护甲"
		L["Unstable Power"] = "能量无常"
		L["Restless Strength"] = "充沛之力"
		L["Ephemeral Power"] = "短暂能量护符"
		L["Massive Destruction"] = "大规模杀伤性魔法"
		L["Arcane Potency"] = "奥术潜能"
		L["Energized Shield"] = "能量护盾"
		L["Brilliant Light"] = "辉煌之光"
		L["Mar'li's Brain Boost"] = "玛尔里的思想加速"
		L["Burst of Energy"] = "能量爆发"
		L["Refocus"] = "重新准备"
		L["Venomous Totem"] = "毒性图腾"
		L["Mind Quickening"] = "思维敏捷"
		L["Gift of Life"] = "生命赐福"
		L["Blinding Light"] = "盲目之光"
		L["Nature Aligned"] = "自然之盟"
		L["Earthstrike"] = "大地之击"
		L["Badge of the Swarmguard"] = "虫群卫士徽章"
		L["Speed"] = "速度"
		L["Immune Root/Snare/Stun"] = "免疫定身/缠绕/昏迷"
		L["Immune Fear/Polymorph/Snare"] = "免疫恐惧/变形/缠绕"
		L["Immune Charm/Fear/Stun"] = "免疫魅惑/恐惧/昏迷"
		L["Immune Charm/Fear/Polymorph"] = "免疫魅惑/恐惧/变形"
		L["Immune Fear/Polymorph/Stun"] = "免疫恐惧/变形/昏迷"
		L["Tidal Charm"] = ""
		L["Diamond Flask"] = ""
		L["Fearless"] = ""
		L["Net-o-Matic"] = ""
		L["The Burrower's Shell"] = ""
		L["Aura of Protection"] = "竞技场大师饰物"
		L["The Eye of the Dead"] = "预知之眼"
		L["Essence of Sapphiron"] = ""
		L["Persistent Shield"] = ""
		L["Slayer's Crest"] = "屠龙者的纹章"
		L["Kiss of the Spider"] = "" 

		L["Frost Reflector"] = "冰霜反射器"
		L["Shadow Reflector"] = "暗影反射器"
		L["Fire Reflector"] = "火焰反射器"
		
		L["Healing Potion"] = "治疗药水"
		L["Healing Draught"] = "治疗药膏"
		L["Restore Mana"] = "恢复法力"
		L["Free Action"] = "自由行动"
		L["Living Free Action"] = "活力自由行动"
		L["Invulnerability"] = "无敌"
		L["Restoration"] = "恢复"
		L["Restore Energy"] = "恢复能量"

		L["Recently Bandaged"] = "新近包扎"
		L["Iron Grenade"] = "铁皮手雷"
		L["Thorium Grenade"] = "瑟银手雷"
		L["Goblin Sapper Charge"] = "地精工兵炸药"
		L["Flash Bomb"] = ""
		L["Arcane Bomb"] = "奥术炸弹"
		
		L["Sleep"] = ""
		L["Flee"] = "逃跑"
		L["Gnomish Rocket Boots"] = "侏儒火箭靴"
		L["Goblin Rocket Boots"] = "地精火箭靴"
		L["Running Speed"] = "跑步速度"
		L["Gnomish Mind Control Cap"] = "侏儒洗脑帽"
		L["Reckless Charge"] = "无畏冲锋"
		L["Sheen of Zanza"] = "赞扎之光"

		-- Warrior
		L["Charge"] = "冲锋"
		L["Mocking Blow"] = "惩戒痛击"
		L["Mortal Strike"] = "致死打击"
		L["Overpower"] = "压制"
		L["Retaliation"] = "反击风暴"
		L["Thunder Clap"] = "雷霆一击"
		L["Berserker Rage"] = "狂暴之怒"
		L["Bloodthirst"] = "嗜血"
		L["Challenging Shout"] = "挑战怒吼"
		L["Intercept"] = "拦截"
		L["Intimidating Shout"] = "破胆怒吼"
		L["Pummel"] = "拳击"
		L["Recklessness"] = "鲁莽"
		L["Whirlwind"] = "旋风斩"
		L["Bloodrage"] = "血性狂暴"
		L["Disarm"] = "缴械"
		L["Revenge"] = "复仇"
		L["Shield Bash"] = "盾击"
		L["Shield Block"] = "盾牌格挡"
		L["Shield Slam"] = "盾牌猛击"
		L["Shield Wall"] = "盾墙"

		-- Paladin
		L["Consecration"] = "奉献"
		L["Exorcism"] = "驱邪术"
		L["Hammer of Wrath"] = "愤怒之锤"
		L["Holy Wrath"] = "神圣愤怒"
		L["Lay on Hands"] = "圣疗术"
		L["Turn Undead"] = "超度亡灵"
		L["Blessing of Freedom"] = "自由祝福"
		L["Blessing of Protection"] = "保护祝福"
		L["Divine Intervention"] = "神圣干涉"
		L["Divine Protection"] = "圣佑术"
		L["Divine Shield"] = "圣盾术"
		L["Hammer of Justice"] = "制裁之锤"
		L["Judgement"] = "审判"
		L["Forbearance"] = "自律"

		-- Mage
		L["Blink"] = "闪现术"
		L["Portal: Darnassus"] = "传送门：达纳苏斯"
		L["Portal: Ironforge"] = "传送门：铁炉堡"
		L["Portal: Orgrimmar"] = "传送门：奥格瑞玛"
		L["Portal: Stormwind"] = "传送门：暴风城"
		L["Portal: Thunder Bluff"] = "传送门：雷霆崖"
		L["Portal: Undercity"] = "传送门：幽暗城"
		L["Blast Wave"] = "冲击波"
		L["Fire Blast"] = "火焰冲击"
		L["Fire Ward"] = "防护火焰结界"
		L["Cone of Cold"] = "冰锥术"
		L["Frost Nova"] = "冰霜新星"
		L["Frost Ward"] = "防护冰霜结界"
		L["Ice Barrier"] = "寒冰护体"
		L["Counterspell"] = "法术反制"
		L["Evocation"] = "唤醒"

		-- Rogues
		L["Kidney Shot"] = "肾击"
		L["Evasion"] = "闪避"
		L["Feint"] = "佯攻"
		L["Gouge"] = "凿击"
		L["Kick"] = "脚踢"
		L["Sprint"] = "疾跑"
		L["Blind"] = "致盲"
		L["Distract"] = "扰乱"
		L["Stealth"] = "潜行"
		L["Vanish"] = "消失"

		-- Shaman
		L["Reincarnation"] = "复生"
		L["Chain Lightning"] = "闪电链"
		L["Earth Shock"] = "地震术"
		L["Earthbind Totem"] = "地缚图腾"
		L["Fire Nova Totem"] = "火焰新星图腾"
		L["Flame Shock"] = "烈焰震击"
		L["Frost Shock"] = "冰霜震击"
		L["Stoneclaw Totem"] = "石爪图腾"
		L["Astral Recall"] = "星界传送"
		L["Grounding Totem"] = "根基图腾"
		L["Mana Tide Totem"] = "法力之潮图腾"

		-- Hunters
		L["Scare Beast"] = "恐吓野兽"
		L["Tranquilizing Shot"] = "宁神射击"
		L["Arcane Shot"] = "奥术射击"
		L["Concussive Shot"] = "震荡射击"
		L["Distracting Shot"] = "扰乱射击"
		L["Flare"] = "照明弹"
		L["Multi-Shot"] = "多重射击"
		L["Rapid Fire"] = "急速射击"
		L["Volley"] = "乱射"
		L["Counterattack"] = "反击"
		L["Disengage"] = "逃脱"
		L["Explosive Trap"] = "爆炸陷阱"
		L["Feign Death"] = "假死"
		L["Frost Trap"] = "冰霜陷阱"
		L["Freezing Trap"] = "冰冻陷阱"
		L["Immolation Trap"] = "献祭陷阱"
		L["Mongoose Bite"] = "猫鼬撕咬"
		L["Raptor Strike"] = "猛禽一击"
		L["Wyvern Sting"] = "翼龙钉刺"

		-- Warlocks
		L["Soulstone Resurrection"] = "灵魂石复活"
		L["Curse of Doom"] = "厄运诅咒"
		L["Death Coil"] = "死亡缠绕"
		L["Howl of Terror"] = "恐惧嚎叫"
		L["Inferno"] = "地狱火"
		L["Ritual of Doom"] = "末日仪式"
		L["Shadow Ward"] = "防护暗影结界"
		L["Conflagrate"] = "燃烧"
		L["Shadowburn"] = "暗影灼烧"
		L["Soul Fire"] = "灵魂之火"
		L["Devour Magic"] = "吞噬魔法"
		L["Spell Lock"] = "法术封锁"
		L["Lash of Pain"] = "剧痛鞭笞"
		L["Soothing Kiss"] = "安抚之吻"

		-- Priest
		L["Elune's Grace"] = "艾露恩的赐福"
		L["Feedback"] = "回馈"
		L["Power Word: Shield"] = "真言术：盾"
		L["Desperate Prayer"] = "绝望祷言"
		L["Fear Ward"] = "防护恐惧结界"
		L["Devouring Plague"] = "噬灵瘟疫"
		L["Fade"] = "渐隐术"
		L["Mind Blast"] = "心灵震爆"
		L["Psychic Scream"] = "心灵尖啸"
		
		-- Druid
		L["Barkskin"] = "树皮术"
		L["Faerie Fire"] = "精灵之火"
		L["Hurricane"] = "飓风"
		L["Nature's Grasp"] = "自然之握"
		L["Bash"] = "重击"
		L["Challenging Roar"] = "挑战咆哮"
		L["Cower"] = "畏缩"
		L["Dash"] = "急奔"
		L["Enrage"] = "狂怒"
		L["Frenzied Regeneration"] = "狂暴回复"
		L["Prowl"] = "潜伏"
		L["Tiger's Fury"] = "猛虎之怒"
		L["Rebirth"] = "复生"
		L["Tranquility"] = "宁静"
		
		-- Interface options
		L["Hide the fist icon: "] = "隐藏拳头图标: "
		L["Check to hide the fist icon."] = "勾选以隐藏拳头图标。"
		L["Show test icons"] = "显示测试图标"
		L["Check to show test icons."] = "勾选以显示测试图标。"
		L["Hide blizzard icon borders"] = "隐藏暴雪图标边框"
		L["Check to hide the blizzard icon borders."] = "勾选以隐藏暴雪图标边框。"
		L["Enable vertical grow"] = "启用垂直增长"
		L["Check to enable vertical grow instead of horizontal."] = "勾选以启用垂直增长而非水平增长。"
		L["Icon size: "] = "图标大小: "
		L["Drag to set icon size"] = "拖动以设置图标大小"
		L["Rows: "] = "行数: "
		L["Drag to set the amount of rows"] = "拖动以设置行数"
		L["Padding: "] = "间距: "
		L["Drag to adjust padding between icons."] = "拖动以调整图标间的间距。"
		L["Reload Variables"] = "重载变量"
		
		-- Bottom instructions
		L["Hold left-click"] = "按住左键"
		L["on the fist button to drag it around."] = "拖动拳头按钮。"
		L["Right-click"] = "右键点击"
		L["the fist button once to enable/disable the addon temporarily."] = "拳头按钮一次以临时启用/禁用插件。"
		L["Shift + Right-click"] = "Shift + 右键点击"
		L["the CD icons will remove them."] = "冷却图标将移除它们。"
			L["Enable stealth notification"] = "启用潜行通报 队伍或团队 (或者聊天框输入 /tb 开启)"
			L["Check to enable stealth notification."] = "勾选以启用潜行通报。"
			L["Enable sound notification"] = "启用语音播报 (或者聊天框输入 /yy 开启)"
			L["Check to enable sound notification."] = "勾选以启用语音播报。"
			L["Enable item debug"] = "启用调试 (开发者专用，请勿勾选)"
			L["Check to enable item debug."] = "临时开启后只输出当前目标的调试信息。开发者专用，默认关闭，不保存勾选状态。"
			
return end
